[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "openubem"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "osmnx >= 1.9, < 2.0",
    "geopandas >= 0.14",
    "shapely >= 2.0",
    "pandas",
    "numpy",
    "pyogrio",
    "packaging",
    "eppy >= 0.5.63, < 1.0",
    "geomeppy >= 0.11.8, < 1.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock",
    "tenacity",
    "pyarrow",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"openubem.data" = ["*.json"]
"openubem.idf" = ["templates/*.idf"]
